### ISSUE TITLE
Enclosed Pipes, Cables, Tubes, Transporters and Conductors

### ISSUE THREAD

**Issue by Peekofwar** [mekanism/Mekanism-Feature-Requests#386] opened 2022-05-06 18:03 UTC
### Describe the feature you'd like

Something that I'd like, is a way to enclose pipes when running them through walls. It's a bit ugly and strange to see a square hole in a wall when pipes are running through it. Especially when it exposes stuff behind the walls (e.g.: a clean white room with a hole in the wall exposing stone and additional wiring behind the wall).

- Enclosed universal cable
- Enclosed mechanical pipe
- Enclosed pressurized tube
- Enclosed logistic transporter
- Enclosed thermodynamic conductor

Perhaps these could be crafted by placing a single cable, pipe, tube, transporter or conductor in a crafting table with a steel casing

![2022-05-06_13 32 50](https://user-images.githubusercontent.com/10189526/167183401-b5f9fffa-699e-4a57-873e-0d37fc360155.png)
![2022-05-06_13 58 19](https://user-images.githubusercontent.com/10189526/167191054-2e700b08-d705-4fa6-84e2-358a137d91cb.png)
![2022-05-06_13 58 27](https://user-images.githubusercontent.com/10189526/167191085-8df7619d-06d8-4da3-8b19-efe06b681f17.png)
![2022-05-06_13 59 05](https://user-images.githubusercontent.com/10189526/167191110-9e011c67-0974-4012-8879-612236dae6e7.png)

**Comment by pupnewfster** [comment] 2022-05-06 18:08
Duplicate of #114

**Closed as completed by pupnewfster** 2022-05-06 18:08 UTC
Labels: duplicate
