### ISSUE TITLE
More uses for antimatter

### ISSUE THREAD

**Issue by Froggy111** [mekanism/Mekanism-Feature-Requests#319] opened 2021-11-24 02:00 UTC
### Describe the feature you'd like

An antimatter generator which takes antimatter gas to generate power. Energy generated is the same as energy needed to make it, same as hydrogen, which makes this a more efficient portable battery.
3 different bombs:
1. A fission bomb (plutonium pellets needed)
2. A fusion bomb (fission bomb + d-t fuel buckets)
3. An antimatter bomb (Antimatter pellet plus some sort of stabaliser) 

### Additional context

Some stuff in mekanism have little use, like antimatter. Even though you can get creative flight and teleportation, and some other uses in the nucleosynthesiser, it is generally pretty useless other than the 2 mekasuit units, so having more uses for antimatter for fun will be quite nice.
Plutonium is also quite useless, since normally fission reactors aren't used to generate power as fusion reactors are so much better, which renders reprocessing quite useless. Therefore, being able to use it for fun stuff will be nice.

**Comment by pupnewfster** [comment] 2021-11-29 02:16
Duplicate of #68 for the generator type thing. And more or less Duplicate of #80 for the bomb type thing, or at least close enough that I am merging it with that, though that is all highly unlikely to happen until Mekanism Defense ends up becoming a thing.

**Closed as completed by pupnewfster** 2021-11-29 02:16 UTC
