### ISSUE TITLE
Laser blaster unit

### ISSUE THREAD

**Issue by Acat1234** [mekanism/Mekanism-Feature-Requests#522] opened 2023-03-10 18:45 UTC
### Describe the feature you'd like

So, a laser blaster unit. That isn't too overpowered and wants to break blocks unless you tell it to That will use FE. And fire on right click A left click melee attack, and a right click laser blast. Makes sense. I think. Can it also make the player point the tool as if it will shoot a laser... if the unit is enabled, can it be compatible with see body in first person mod so look great please?

**Comment by pupnewfster** [comment] 2023-03-10 19:15
Closing this as a duplicate of #521 (the other issue you opened)

**Closed as not planned by pupnewfster** 2023-03-10 19:15 UTC
