### ISSUE TITLE
Replace or Supplement Dosimeter unit with Geiger Counter Unit

### ISSUE THREAD

**Issue by TheInfamousAlk** [mekanism/Mekanism-Feature-Requests#321] opened 2021-11-28 20:22 UTC
### Describe the feature you'd like

So the mekasuit is great. However I found the dosimeter unit to be a bit strange. If you have radiation shielding on all armor parts, you should never absorb any radiation. So I find it strange that the only upgrade regarding radiation detection shows how much you absorb rather than how much is in the environment. I think a geiger counter HUD display would be much more useful than the dosimeter unit. But the best would be having both as 2 optional upgrades.

### Describe alternatives you've considered

The alternative would be carrying around a geiger counter with you while you can see the dosimeter on your hud. Kind of feels bad carrying around that extra item when the dosimeter can be displayed on the HUD with no item.

**Comment by pupnewfster** [comment] 2021-11-28 20:25
Duplicate of #185

**Closed as completed by pupnewfster** 2021-11-28 20:25 UTC
