### ISSUE TITLE
Machine and Reactor Monitoring

### ISSUE THREAD

**Issue by Bobnotbuilder** [mekanism/Mekanism-Feature-Requests#644] opened 2024-03-05 23:20 UTC
### Describe the feature you'd like

Display Screens which allow you to monitor fission, fusion and machine activities. Allowing for touch controls to interact with the machines the screens are monitoring. 

Similar to computercraft but a Mekanism version already to go, just connect them the machine and a way we go.

### Additional context

Features: 
The computer craft integration handles such as getFeulpercentage can be used to get all desired information for the display screens.

Redstone control, when a button on the screen is pressed a redstone signal is sent out allowing for individual machine control.

The aim is to keep it simple yet intimuative, each machine/reactor, SPS could have its own pre determined screen layout and the user can toggle what they want to see.

**Comment by pupnewfster** [comment] 2024-03-10 19:43
Duplicate of other open feature requests

**Closed as not planned by pupnewfster** 2024-03-10 19:43 UTC
