### ISSUE TITLE
Curios Slot for HDPE Elytra

### ISSUE THREAD

**Issue by Lion4K** [mekanism/Mekanism-Feature-Requests#445] opened 2022-08-31 18:46 UTC
### Describe the feature you'd like

A Slot to be able to use your HDPE Elytra on a Curios Slot.
https://www.curseforge.com/minecraft/mc-mods/curios

**Comment by pupnewfster** [comment] 2022-08-31 18:50
Duplicate of #391

**Closed by pupnewfster** 2022-08-31 18:50 UTC
