### ISSUE TITLE
Upload Mekanism to Modrinth

### ISSUE THREAD

**Issue by waddon1** [mekanism/Mekanism-Feature-Requests#368] opened 2022-04-12 09:27 UTC
### Describe the feature you'd like

Would it be possible for Mekanism to get releases on Modrinth? It's a new open source minecraft modding platform and I feel mekanism should be on there. https://modrinth.com/

**Comment by Matyrobbrt** [comment] 2022-04-12 09:47
Duplicate of #348

**Closed as completed** 2022-04-12 10:00 UTC
