### ISSUE TITLE
Change the Color of MekaSuits?

### ISSUE THREAD

**Issue by awbuckst11181999** [mekanism/Mekanism-Feature-Requests#167] opened 2021-01-16 05:55 UTC
Back in ye old days of modular powersuits, you could change the color of the suits as you wanted, and I think it would make a great addition to the mekasuits as well.

I didn't see any other suggestions when searching, so forgive me if this has been suggested already.

**Comment by pupnewfster** [comment] 2021-01-16 14:15
Basically a duplicate of #72

**Closed by pupnewfster** 2021-01-16 14:15 UTC
