### ISSUE TITLE
Digital Farmer

### ISSUE THREAD

**Issue by Zix375** [mekanism/Mekanism-Feature-Requests#346] opened 2022-01-24 00:03 UTC
### Describe the feature you'd like

Mekanism takes out the hassle of mining and needs to search for specific blocks via the Digital miner. This also allows you to harvest Trees. 

An advanced block that allows you to grow trees/crops faster than a vanilla speed. 

Examples include: Garden Cloche - Immersive Engineering, Bonsai Pots

**Comment by pupnewfster** [comment] 2022-01-24 00:08
Duplicate of #51/#301, though honestly I am leaning more towards something like Calculator's greenhouse (multiblock structure) if/when I ever get around to implementing something for farming.

**Closed as completed by pupnewfster** 2022-01-24 00:08 UTC
