### ISSUE TITLE
PLEASE PLEASE PLEASE add disguising features 

### ISSUE THREAD

**Issue by sapphic-agent-4** [mekanism/Mekanism-Feature-Requests#196] opened 2021-02-13 21:13 UTC
u guys seem to be the only good tech mod in 1.16 packs these days so im imploring you to A) add covers for the different kinds of pipes so i can hide them behind walls and B) let me make the meka-suit invisible. i dont mean to be insulting but it is soooooooooo ugly. idk whether its some kind of social commentary on the technological progression of society or whatever but its almost unusable because of how horrendous it looks. 
thank u for being so understanding <3

**Comment by sapphic-agent-4** [comment] 2021-02-13 21:22
i dont mean 2 be rude but everything is so ugly! how am i supposed to build a cool base AND have cool tech?

**Comment by pupnewfster** [comment] 2021-02-13 21:54
Closing as this is basically a duplicate of https://github.com/mekanism/Mekanism-Feature-Requests/issues/114

**Closed by pupnewfster** 2021-02-13 21:54 UTC
