### ISSUE TITLE
Make Acids and Other liquids have properties 

### ISSUE THREAD

**Issue by VxBlx** [mekanism/Mekanism-Feature-Requests#389] opened 2022-05-23 12:27 UTC
### Describe the feature you'd like

Basically instead of the white liquid have colored buckets for each fluid (DT-Fuel would be like a purple water) and some would have special Properties EX: Sulfuric acid hurts you like lava, plutonium or anything radioactive emits radioactivity.

**Comment by pupnewfster** [comment] 2022-05-23 16:32
Duplicate of #59

**Closed as completed by pupnewfster** 2022-05-23 16:32 UTC
Labels: duplicate
