### ISSUE TITLE
QIO Autocrafting and external storage

### ISSUE THREAD

**Issue by lisekilis** [mekanism/Mekanism-Feature-Requests#358] opened 2022-03-08 13:30 UTC
If autocrafting and external storage(similar to ME interfaces and stuff ex. connecting a BIN to your qio system for bulk item storage) similar to AE2 could be implemented it would be absolutely wonderful.

Alternatively just the external storage(similar to ME interface and ME external storage) just so u could use ae2 for autocrafting and set the qio as the external storage of your AE2 system.

**Comment by NullPointerCollection** [comment] 2022-03-08 13:42
Duplicate of https://github.com/mekanism/Mekanism-Feature-Requests/issues/229

Please check before making requests

**Closed as completed** 2022-03-08 15:08 UTC
