### ISSUE TITLE
Ability to black list items in Logistical Sorter

### ISSUE THREAD

**Issue by lhill123** [mekanism/Mekanism-Feature-Requests#270] opened 2021-07-14 02:18 UTC
### Describe the feature you'd like

I would like the "invert" function which is currently available in the filter for the Digital Miner to be added to the Logistical Sorter.

### Describe alternatives you've considered

As far as I know a viable alternative does not currently exist.

### Additional context

Adding this function to the Logistical Sorter will provide the ability to create a black list of items which the logistical sorter may not pass. This will provide the ability to stop items from leaving a chest via a particular sorter, thereby forcing them to leave the chest via the sorter which white lists them. Adding this feature will give the ability to create a system to sort a large number of items into individual chests. Consider a situation where a digital miner outputs everything to a double chest. In practical terms you have space to connect a single input to and 5 outputs from the chest. Each of the 5 outputs consists of a Logistical Sorter. 4 of the Logistical Sorters each have a single filter specifying an ore which may pass through to an attached chest. The 5th sorter has each of these 4 ores black listed so that their only exit route is through the sorter which lists them in a filter. The 5th Logistical Sorter then outputs all remaining items from the chest. This may then be repeated through multiple stages in order to sort a large number of items into separate chests.

**Comment by pupnewfster** [comment] 2021-07-14 02:20
Duplicate of #3

**Closed as completed by pupnewfster** 2021-07-14 02:20 UTC
